# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatResult',
            fields=[
                ('catcode', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('batseats', models.IntegerField(default=1)),
                ('batcount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BatterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('1', 'P'), ('2', 'C'), ('3', '1B'), ('4', '2B'), ('5', '3B'), ('6', 'SS'), ('7', 'LF'), ('8', 'CF'), ('9', 'RF'), ('DH', 'DH')], max_length=2)),
                ('batseat1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat1', to='playgame.BatResult')),
                ('batseat2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat2', to='playgame.BatResult')),
                ('batseat3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat3', to='playgame.BatResult')),
                ('batseat4', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat4', to='playgame.BatResult')),
                ('batseat5', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat5', to='playgame.BatResult')),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_title', models.CharField(max_length=30)),
                ('is_finished', models.BooleanField(default=False, verbose_name='季賽結束')),
            ],
        ),
        migrations.CreateModel(
            name='CupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=2)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.Cup')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dif_date', models.DateField()),
                ('playdate', models.DateField()),
                ('guest_score', models.IntegerField(default=0)),
                ('home_score', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False, verbose_name='')),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.Cup')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.Team')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='playgame.Team'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='playgame.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.Schedule'),
        ),
        migrations.AddField(
            model_name='cupgroup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.Team'),
        ),
        migrations.AddField(
            model_name='batterorder',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.Member'),
        ),
        migrations.AddField(
            model_name='batterorder',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.Schedule'),
        ),
        migrations.AddField(
            model_name='batterorder',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('cup', 'guest', 'home')]),
        ),
        migrations.AlterUniqueTogether(
            name='cupgroup',
            unique_together=set([('cup', 'team', 'group')]),
        ),
    ]
