# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgame', '0002_cup_league'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cup',
            options={'ordering': []},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='比賽完成'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='會員資格'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='可登錄'),
        ),
    ]
