# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgame', '0004_auto_20180328_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterorder',
            name='position',
        ),
    ]
