# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-04 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playgame', '0005_remove_batterorder_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterorder',
            name='team',
        ),
        migrations.AddField(
            model_name='batterorder',
            name='is_Home',
            field=models.BooleanField(default=False),
        ),
    ]
