# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playgame', '0006_auto_20180404_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgame.League')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playgame.Place'),
            preserve_default=False,
        ),
    ]
