# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playgame', '0007_auto_20180405_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterorder',
            name='batseat1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat1', to='playgame.BatResult'),
        ),
        migrations.AlterField(
            model_name='batterorder',
            name='batseat2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat2', to='playgame.BatResult'),
        ),
        migrations.AlterField(
            model_name='batterorder',
            name='batseat3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat3', to='playgame.BatResult'),
        ),
        migrations.AlterField(
            model_name='batterorder',
            name='batseat4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat4', to='playgame.BatResult'),
        ),
        migrations.AlterField(
            model_name='batterorder',
            name='batseat5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat5', to='playgame.BatResult'),
        ),
    ]
